### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by HoldenA1** [20-20REENVISIONED/Refactored-fortune-teller#1]
- [x] Document the existing CI/CD pipeline noting any issues or problems with the current design
- [ ] Add file headers to give a short description of what each file does
- [ ] Create a map or diagram that gives an overview of how all of the files interact with one another (we mentioned choosing some diagram generator to automatically update the diagram when changes are pushed so this is worth looking into)

**Comment by hhcoxatucsd** [comment]
Documented the CI/CD pipeline in using Github's Wiki [here](https://github.com/20-20REENVISIONED/Refactored-fortune-teller/wiki/CI-CD-Pipeline).
