### ISSUE TITLE
Update the Background Image/Card Container Images

### ISSUE THREAD

**Issue by JosephBurger** [20-20REENVISIONED/Refactored-fortune-teller#15]
I will be updating the application's UI by replacing outdated background images and card container images with newly generated ones. This update aims to enhance the visual appeal and user experience, ensuring a modern and cohesive design throughout the application. By carefully selecting and integrating high-quality images, we aim to create a more immersive and engaging environment for users.

**Comment by hhcoxatucsd** [comment]
If you haven't gotten around to this yet, please merge at least up to commit `fb42aaf9e43f69b61462f49a4f3e10601606b91c` from the `feat/performance` branch into yours. I added `<picture>` tags for performance and you'll want to put in jpeg (if no transparency), webp and avif versions of your images. I can also be the one to do this if you'd kindly push the applicable branch to github.
