### ISSUE TITLE
Accessability: Navigation and usage only by keyboard not possible

### ISSUE THREAD

**Issue by hhcoxatucsd** [20-20REENVISIONED/Refactored-fortune-teller#27]
It's not possible to use the app using only your keyboard. In love compatibility, you cannot rotate the wheels unless you have a mouse. If you select the `How to use` as well, you get trapped there and cannot close the popup. In Palm reading, it's not possible to switch the tabs from your reading result

**Comment by jheidenr** [comment]
Tasks:

Love Compatibility Page:
- [x] Allow the wheels to be controlled by keyboard
- [x] Fix the button in the "How to Use" window

Palm Reading Page:
- [ ] Allow the user to switch tabs via keyboard

**Comment by arnavkamra14** [comment]
Was not able to address. May be a good starting point for future groups who wish to improve upon this project.
