### ISSUE TITLE
Make site into a PWA

### ISSUE THREAD

**Issue by HoldenA1** [20-20REENVISIONED/Refactored-fortune-teller#4]
Make site installable as a [Progressive Web App](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) with offline access

This task involves writing a manifest.json which defines certain properties of the app, writing service workers to handle caching files and installation of the app, and lastly making the app work properly offline (this can be achieved by disabling features which need the internet or finding a way to get them to work while offline).

**Comment by arnavkamra14** [comment]
Was not able to be addressed
