### ISSUE TITLE
Optimize loading latency

### ISSUE THREAD

**Issue by HoldenA1** [20-20REENVISIONED/Refactored-fortune-teller#7]
- [ ] Setup of a CI/CD pipeline that automatically flattens html,css and javascript files into one file html file to reduce ping-ponging (latency). Maybe use something like [this](https://github.com/remy/inliner)
- [x] Optimize images
- [ ] Replace `love-compatibility/images/arrow-left` and `arrow-right` with svgs and maybe `close` too.
- [ ] Replace hardcoded images in the CSS and JS to use the proper image (ie do the equivalent of the `<picture>` tag)

**Comment by hhcoxatucsd** [comment]
We might want to consider upping the priority on this one:

https://github.com/20-20REENVISIONED/Refactored-fortune-teller/assets/138736493/3c77fda5-d64e-4b1a-8506-d4b19de1932e

**Comment by HoldenA1** [comment]
Couldn't agree more. I'll work on this before the PWA enhancement.

**Comment by HoldenA1** [comment]
Did some ad-hoc performance testing with chrome throttling on mobile and the features were still decently fast, so I chose to drop this task, but might be good to revisit later.
